print("Please enter a character for the eye:")
eye = input()
print("Beep's expresion is now as follow:")
print("    __________   ")
print("    |",  eye,"  ", eye,"|") 
print("    |        |       ")
print("    |  ====  |")
print("    \________/")
print(" ______|___|______")
print("()__)          ()_)")
print("// / |         |\  \ ")
print("|  | |         | \  \ ")
print("(++) ()_______()  (++)")
print("      ___(__)__   ")
print("     | /     \ |")
print("     | |     | |   ")
print("     ( )     ( )")
print("     | |     | |")
print("    /___\   /___\ ")